import { Network } from "bitcoinjs-lib";
import { ContractLoader } from "../contract/contract-loader";
import { AssetDao } from "../dao/asset-dao";
import { AssetSupplyDao } from "../dao/asset-supply-dao";
import { OpCommitDao } from "../dao/commit-dao";
import { DepositDao } from "../dao/deposit-dao";
import { OpEventDao } from "../dao/event-dao";
import { FeeRateDao } from "../dao/feerate-dao";
import { MatchingDao } from "../dao/matching-dao";
import { PoolListDao } from "../dao/pool-list-dao";
import { RecordApproveDao } from "../dao/record-approve-dao";
import { RecordGasDao } from "../dao/record-gas-dao";
import { RecordLiqDao } from "../dao/record-liq-dao";
import { RecordSendDao } from "../dao/record-send-dao";
import { RecordSwapDao } from "../dao/record-swap-dao";
import { SequencerTxDao } from "../dao/sequencer-tx-dao";
import { SequencerUtxoDao } from "../dao/sequencer-utxo-dao";
import { SnapshotAssetDao } from "../dao/snapshot-asset-dao";
import { SnapshotKLastDao } from "../dao/snapshot-klast-dao";
import { SnapshotSupplyDao } from "../dao/snapshot-supply-dao";
import { StatusDao } from "../dao/status-dao";
import { TickDao } from "../dao/tick-dao";
import { WithdrawDao } from "../dao/withdraw-dao";
import { API } from "../domain/api";
import { Builder } from "../domain/builder";
import { ConditionalWithdraw } from "../domain/conditional-withdraw";
import { Decimal } from "../domain/decimal";
import { Deposit } from "../domain/deposit";
import { Env } from "../domain/env";
import { Keyring } from "../domain/keyring";
import { Matching } from "../domain/matching";
import { Metric } from "../domain/metric";
import { Operator } from "../domain/operator";
import { Query } from "../domain/query";
import { Sender } from "../domain/sender";
import { Statistic } from "../domain/statistic";
import { DirectWithdraw } from "../domain/withdraw";
import { DateLogger } from "../utils/logger";
import { MongoUtils } from "../utils/mongo-utils";
import { Config } from "./domain";

declare global {
  var fatal: boolean;
  var inited: boolean;
  var network: Network;
  var config: Config;
  var mongoUtils: MongoUtils;
  var sender: Sender;
  var builder: Builder;
  var operator: Operator;
  var api: API;
  var decimal: Decimal;
  var query: Query;
  var env: Env;
  var logger: DateLogger;
  var contractLoader: ContractLoader;
  var deposit: Deposit;
  var conditionalWithdraw: ConditionalWithdraw;
  var directWithdraw: DirectWithdraw;
  var matching: Matching;
  var keyring: Keyring;
  var metric: Metric;
  var statistic: Statistic;

  var opCommitDao: OpCommitDao;
  var opEventDao: OpEventDao;
  var tickDao: TickDao;
  var recordLiqDao: RecordLiqDao;
  var recordSwapDao: RecordSwapDao;
  var recordApproveDao: RecordApproveDao;
  var recordSendDao: RecordSendDao;
  var sequencerUtxoDao: SequencerUtxoDao;
  var sequencerTxDao: SequencerTxDao;
  var withdrawDao: WithdrawDao;
  var matchingDao: MatchingDao;
  var depositDao: DepositDao;
  var recordGasDao: RecordGasDao;
  var feeRateDao: FeeRateDao;
  var statusDao: StatusDao;
  var snapshotAssetDao: SnapshotAssetDao;
  var snapshotKLastDao: SnapshotKLastDao;
  var snapshotSupplyDao: SnapshotSupplyDao;
  var assetDao: AssetDao;
  var assetSupplyDao: AssetSupplyDao;
  var poolListDao: PoolListDao;
}

export {};
