import { Network } from "bitcoinjs-lib";
import { ContractLoader } from "../contract/contract-loader";
import { DepositDao } from "../dao/deposit-dao";
import { MatchingDao } from "../dao/matching-dao";
import { OpCommitDao } from "../dao/op-commit-dao";
import { OpConfirmDao } from "../dao/op-confirm-dao";
import { OpListDao } from "../dao/op-list-dao";
import { RecordApproveDao } from "../dao/record-approve-dao";
import { RecordGasDao } from "../dao/record-gas-dao";
import { RecordLiqDao } from "../dao/record-liq-dao";
import { RecordSendDao } from "../dao/record-send-dao";
import { RecordSwapDao } from "../dao/record-swap-dao";
import { SequencerTxDao } from "../dao/sequencer-tx-dao";
import { SequencerUtxoDao } from "../dao/sequencer-utxo-dao";
import { TickDao } from "../dao/tick-dao";
import { WithdrawDao } from "../dao/withdraw-dao";
import { API } from "../domain/api";
import { Decimal } from "../domain/decimal";
import { Deposit } from "../domain/deposit";
import { Env } from "../domain/env";
import { Keyring } from "../domain/keyring";
import { Matching } from "../domain/matching";
import { Metric } from "../domain/metric";
import { OpBuilder } from "../domain/op-builder";
import { OpSender } from "../domain/op-sender";
import { Operator } from "../domain/operator";
import { Query } from "../domain/query";
import { Statistic } from "../domain/statistic";
import { Withdraw } from "../domain/withdraw";
import { DateLogger } from "../utils/logger";
import { MongoUtils } from "../utils/mongo-utils";
import { Config } from "./domain";

declare global {
  var fatal: boolean;
  var inited: boolean;
  var network: Network;
  var config: Config;
  var mongoUtils: MongoUtils;
  var opSender: OpSender;
  var opBuilder: OpBuilder;
  var operator: Operator;
  var api: API;
  var decimal: Decimal;
  var query: Query;
  var env: Env;
  var logger: DateLogger;
  var contractLoader: ContractLoader;
  var deposit: Deposit;
  var withdraw: Withdraw;
  var matching: Matching;
  var keyring: Keyring;
  var metric: Metric;
  var statistic: Statistic;

  var opCommitDao: OpCommitDao;
  var opConfirmDao: OpConfirmDao;
  var opListDao: OpListDao;
  var tickDao: TickDao;
  var recordLiqDao: RecordLiqDao;
  var recordSwapDao: RecordSwapDao;
  var recordApproveDao: RecordApproveDao;
  var recordSendDao: RecordSendDao;
  var sequencerUtxoDao: SequencerUtxoDao;
  var sequencerTxDao: SequencerTxDao;
  var withdrawDao: WithdrawDao;
  var matchingDao: MatchingDao;
  var depositDao: DepositDao;
  var recordGasDao: RecordGasDao;
}

export {};
